### ISSUE TITLE
Implement UUID detection (Sprint-1 Example Issue)

### ISSUE THREAD

**Issue by claesmk** [NCATComp410/comp410_summer_2023#1]
**Description:**
A [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) or universally unique identifier can potentially be used to personally identify an individual. 

While there can be multiple types of UUIDs, this issue will focus on the 8-4-4-4-12 format, for example:

```
123e4567-e89b-12d3-a456-426652340000 
```

**Detection Steps:**
Python code will be developed which will detect hexadecimal numbers in the 8-4-4-4-12 format

**Comment by Natalyapolite** [comment]
When is the UUID invalid ?

**Comment by claesmk** [comment]
> When is the UUID invalid ?

The goal here is to detect a potential UUID in the 8-4-4-4-12 format.  Any hex string in this format could be considered valid, as far as I know, per the RFC

**Comment by ncholliday** [comment]
What is a real-world example of a UUID that uses hexadecimal numbers?

**Comment by claesmk** [comment]
One application for UUID is when generating a credit card transaction - see [this](https://doc.toasttab.com/doc/devguide/authorizingCcPayments.html) developer's guide for more details
