### ISSUE TITLE
Implement Banner Identification Number Detection

### ISSUE THREAD

**Issue by adomakk** [NCATComp410/comp410_summer_2023#12]
****Definition**:** 
A Banner Identification Number (often referred to as Banner ID) is a unique number assigned to each student, faculty, or staff member in a school or university that uses the Banner system by Ellucian or similar software. This ID number is used within the system for various administrative tasks, including registration, grade reporting, and access to personal records. The Banner ID is considered Personally Identifiable Information (PII) because it uniquely identifies an individual within the institution's system. While it may not reveal much about a person on its own, when combined with other data points, it could be used to gain access to sensitive information such as academic records, financial data, or personal contact information. The unauthorized access, use, or disclosure of Banner ID numbers could have significant consequences. These might include identity theft, fraudulent access to sensitive personal or financial information, or potentially altering academic records. Therefore, it's essential to protect this type of PII from data breaches and unauthorized access.

****Example**:**
950000000, 950100000, 950200000, 950754556, 345643, 675643

**Detection Steps:**
Python code will be developed which will detect a string that matches a valid Banner ID format. This code will initially be configured to check for a Banner ID that consists of 6 digits or more, which is specific to certain illustrious university. However, the detection criteria can be easily adjusted to match the Banner ID format of any other educational institution. This adaptability will enable the code to identify any string in the text that corresponds to the format of a Banner ID, no matter the specific pattern used by the school.

**Comment by aalston2** [comment]
I think you're working on yours but don't forget to add yourself as an assignee. also I like the banner ID idea. do you think simplifying might be better? Cause I know alot of places only ask for the last 6 digits of your banner at the school.

**Comment by aalston2** [comment]
disregard the above about 950 cause you already thought about  it

**Comment by claesmk** [comment]
> '950' followed by a '#' symbol, which is specific to certain

I don't see this symbol in any of your examples?  Can you give an example of what this would look like? 

I'm also concerned about what @aalston2 said - do you have any examples of using only the last 6 digits?  Is that because if you are within a certain school the prefix (950#) would be assumed?  For example, if you knew someone was a student at A&T and you had the last six digits, could you ID them?

**Comment by adomakk** [comment]
> I think you're working on yours but don't forget to add yourself as an assignee. also I like the banner ID idea. do you think simplifying might be better? Cause I know alot of places only ask for the last 6 digits of your banner at the school.

You're right, I'll make the code only ask for the last 6 digits, since the first few are the same for most Student IDs. Thank you!

**Comment by adomakk** [comment]
> > '950' followed by a '#' symbol, which is specific to certain
> 
> I don't see this symbol in any of your examples? Can you give an example of what this would look like?
> 
> I'm also concerned about what @aalston2 said - do you have any examples of using only the last 6 digits? Is that because if you are within a certain school the prefix (950#) would be assumed? For example, if you knew someone was a student at A&T and you had the last six digits, could you ID them?

I took out the symbol from the description, I realized I didn't really need it and yes you can ID a student from their last six digits. I'll make the code only ask for 6 digits since this is the case.

**Comment by adomakk** [comment]
Actually, I'll include it all so that it can detect whether they include 950 or not!
