### ISSUE TITLE
Implement Social Security Detection

### ISSUE THREAD

**Issue by nsmiller1** [NCATComp410/comp410_summer_2023#14]
Description:  A Social Security number (SSN) is a unique nine-digit identifier issued by the Social Security Administration (SSA) within the United States. It is used primarily to track individuals' earnings and work history for the purpose of administering Social Security benefits. Given the importance of Social Security numbers in identity verification and various financial and governmental processes, it's crucial to safeguard your SSN and use it only when necessary. Protecting your 

Format: XXX-XX-XXXX
Mostly found on an SSN card

Example: 
John's Social Security number is 123-45-6789. 

Detection Steps: To identify an SSN, regular expressions or pattern-matching algorithms are used to identify strings that match the format of a Social Security number. An SSN typically follows the pattern of three digits, followed by two digits, and then four digits. Searching for this pattern in a text or data source may detect potential SSNs.

**Comment by claesmk** [comment]
This is a duplicate of this [issue](https://github.com/NCATComp410/comp410_summer_2023/issues/4) Per the assignment instructions, no duplicate issues are allowed

> 2. Individually, choose one specific type of personally identifiable information (e.g., name, email address, US phone number, social security number, etc.) to focus on for this assignment.  No duplicate issues are allowed.  For example, if you want to work on US phone numbers but someone has already created an issue for that, you must pick a different type of PII.  

Please close this issue, pick a different type of PII, and create a new issue for that
