### ISSUE TITLE
Implement Medical Records Detection

### ISSUE THREAD

**Issue by nsmiller1** [NCATComp410/comp410_summer_2023#19]
Description: Medical records are documents that contain a comprehensive record of a patient's medical history, including information related to their health, diagnoses, treatments, medications, and interactions with healthcare providers. These records are created and maintained by healthcare professionals and organizations involved in a patient's care, such as hospitals, clinics, doctors, nurses, and specialists. Patient privacy and confidentiality are essential aspects of medical records, and strict security measures are implemented to protect this sensitive information.

Format: There are three types of medical records commonly used by patients and doctors:
Personal health record (PHR)
Electronic medical record (EMR)
Electronic health record (EHR)

Example: 
Patient demographics: Name, date of birth, gender, contact information, and emergency contact details.
Medical history: Past and current medical conditions, surgeries, hospitalizations, allergies, and family medical history.
Medication list: A comprehensive list of medications the patient is currently taking, including prescription drugs, over-the-counter medications, vitamins, and supplement

Detection Steps: Determine which healthcare provider or facility holds your medical records. This could be a primary care physician, specialist, hospital, clinic, or any other healthcare organization you have visited in the past. Reach out to the healthcare provider's office or medical records department. You can do this via phone, email, or in person. Inquire about the process for requesting your medical records and ask for any necessary forms or documentation.

**Comment by claesmk** [comment]
Decided not to implement this
