### ISSUE TITLE
Phone number test case commented out

### ISSUE THREAD

**Issue by claesmk** [NCATComp410/comp410_summer_2023#29]
Why was this particular [test case](https://github.com/NCATComp410/comp410_summer_2023/blob/6a80fe8f1a19d548e2674973a26e010e23b3bec5/test_pii_scan.py#L76) commented out?

        #results = analyze_text('+1(999)222-444')
        #self.assertIn('PHONE_NUMBER', str(results))

**Comment by ncholliday** [comment]
When I test it, i did failed. I think the plus sign was not accepted.

**Comment by ncholliday** [comment]
When I tested that case, it failed. The test didn’t run. I think the plus sign was not accepted.

**Comment by ncholliday** [comment]
When I tested that case, it failed. The test didn’t run. I think the plus sign was not accepted.
