### ISSUE TITLE
Implement Drivers License Detection

### ISSUE THREAD

**Issue by nsmiller1** [NCATComp410/comp410_summer_2023#32]
Description: A driver's license typically contains the holder's personal information, including their full name, date of birth, address, and photograph. It also includes essential details such as the license number, issue and expiration dates, and any specific restrictions or endorsements. It proves that the holder has completed the necessary requirements, such as passing a driving test and meeting exact age and medical criteria, to drive a car, motorcycle, or other motorized vehicle. They are generally required to be carried by drivers while operating a vehicle.

Format: Driver's licenses are commonly used as a form of identification, and they vary in appearance and format depending on the country or state issuing them. Including name, DOB, expiration date, and ID number

Example: 
Nadir Miller 
03/18/2001
03/18/2040
000012345678

Detection Steps: Look for Holograms and Security Features: Many driver's licenses include holographic elements, such as holographic overlays, holographic images, or microprinting. Check for Watermarks: Hold the license up to a light source and look for watermarks or embedded images. Validate Security Features with a Light Source: Some licenses have additional security features that are visible under ultraviolet (UV) light.

**Comment by claesmk** [comment]
[This](https://ntsi.com/drivers-license-format/) is a good reference for driver's license number formats
