### ISSUE TITLE
Implement Social Security Number Detection 

### ISSUE THREAD

**Issue by Natalyapolite** [NCATComp410/comp410_summer_2023#4]
**Description:** 
Detecting and protecting a social security number (SSN) is of utmost importance due to its critical role in personal identification and the potential for severe consequences if it falls into the wrong hands. You use your social security number for so many everyday tasks including identity verification, preventing identity theft, maintaining financial security, preventing medical identity theft, combating government benefits fraud, facilitating legal processes, and preserving personal privacy. Safeguarding this unique identifier helps individuals protect their personal and financial well-being, ensuring they have control over their identity and reducing the risks associated with unauthorized access to their personal information.

For example:

`111-11-1111`

**Detection Steps:**
Python code will be developed which will detect a string that will match a valid social security format. This code will check to if the social security consists of any 3 combination of numbers following a hyphen followed by any pair of numbers following a hyphen ended by any 4 combination of numbers.

**Comment by jrbonds** [comment]
Issue reviewed.

**Comment by claesmk** [comment]
Keep in mind during your testing that you should attempt to use numbers which cannot possibly be valid.  Your example is likely not valid, but there is nothing in the [specification](https://www.ssa.gov/policy/docs/ssb/v69n2/v69n2p55.html) which prevents it from being valid.  It's safe to always use a group number 00, for example 111-00-1111

**Comment by Natalyapolite** [comment]
Thank you for the feedback @claesmk. I will ensure to implement this when testing.

**Comment by claesmk** [comment]
@Natalyapolite the reason you were not able to change the label and milestone yourself is because you have not accepted the invitation to join the class [team](https://github.com/orgs/NCATComp410/teams/comp410summer2023class) yet.  It should be in your email, maybe a spam folder

**Comment by Natalyapolite** [comment]
Hi! @claesmk I am following the recording uploaded for sprint 2 and under "Development" I do not see an option to create a branch. Is there another way to do so?

**Comment by claesmk** [comment]
The issues is that you need to accept the invitation from GitHub to joint the [Summer2023](https://github.com/orgs/NCATComp410/teams/comp410summer2023class) team.  Once you do that these options will be available.
