### ISSUE TITLE
Implement Phone Number Detection

### ISSUE THREAD

**Issue by ncholliday** [NCATComp410/comp410_summer_2023#5]
Description: 
Detecting and protecting a phone number is crucial in today's digital age where communication is predominantly facilitated through mobile devices. Detecting and protecting a phone number is essential for maintaining effective communication, fostering personal and professional relationships, ensuring personal security, preventing scams and fraud, preserving privacy, managing reputation, and facilitating emergency assistance. Safeguarding this crucial contact information allows individuals to maintain control over their digital presence, protect their personal information, and enhance their overall security and well-being.

For example:

`999-222-4444`

Detection Steps:
Python code will be developed which will detect decimal numbers in the  XXX-XXX-XXXX format. The hyphen will be included in the accepted characters that will be inputted into the code.

**Comment by claesmk** [comment]
Many people write their phone number as 336.555.1212 or (336)555-1212.  I think these cases need to be handled as well

**Comment by ncholliday** [comment]
Thank you, that is very common and valid. There are some cases where prompts only allow number (ex. 4104439082). Do you think it should also handle just all numbers? @claesmk

**Comment by claesmk** [comment]
That's a great observation.  I think it's a great idea to also recognize a 10-digit number as a phone number

**Comment by ncholliday** [comment]
Thank you!
