### ISSUE TITLE
Implement Credit Card Number Detection

### ISSUE THREAD

**Issue by brmtalla** [NCATComp410/comp410_summer_2023#6]
**Description**

ChatGPT is a powerful language model capable of generating human-like responses to user inputs. However, there is a risk that the model might inadvertently generate or extract credit card numbers from the user's input, which could pose a significant security and privacy concern. To ensure the protection of user information, it is essential to implement measures that prevent the detection and propagation of credit card numbers by ChatGPT. There is a concern regarding the potential risk of Credit Card Number (CCN) detection when using the platform. This issue aims to address this concern by implementing a reliable mechanism to prevent the accidental exposure of sensitive credit card information during conversations with ChatGPT.

For example:
> 4444-5555-6666-7777

**Detection Steps**
The proposed solution involves integrating a credit card number detection mechanism using Python. This mechanism will analyze user inputs in real-time, identifying and filtering out any credit card numbers before they are processed by the language model. The detection mechanism can be implemented by designing code for this purpose that detects a 16 digit number, reads the first 6 numbers and rejects its implementation into returning a response if they match a Bank Identification Number.

**Comment by claesmk** [comment]
> The detection mechanism can be implemented by designing code for this purpose that detects a hexadecimal hash that matches the XXXX-XXXX-XXXX-XXXX format

A credit card number would not have a hexadecimal hash, it would be digits 0..9 

What about an AMEX card?  Do you plan to detect that or would that not be part of this requirement?
