### ISSUE TITLE
Implement IPv4 Address Detection

### ISSUE THREAD

**Issue by aalston2** [NCATComp410/comp410_summer_2023#7]
**Description:** A user's IP address is one of the most critically important pieces of information a user has to protect while online. Thief of the IP address can lead to location and information leaks that will be used by attackers to gain access to crucial information that the address holder owns

Example:
XXX.XXX.XXX.XXX or 123.321.456.654
_X in this case represents a digit for each of the 4 sections_

Detection Steps: the users can use numerical symbols to put in place detection strategies that will ensure correct handling and usage of their IP address. The Python code will identify a user's IP by examining each, up to 3 digit, section of their IP addresses. If the code reads IP examples that have 4 digits sections or has none numeric symbols it will not be considered a valid IP address. 
**Valid example:** 123.321.456.654
 **Nonvalid example:** @31.5673.9T2.1O1

**Comment by claesmk** [comment]
>  IP. IE ( 123."131".10.01)

Not sure how to interpret this example, could you explain it a little better?

**Comment by aalston2** [comment]
oh my apologies. I'm referring to each of the four sections of the IP. I'll be using IPv4 (which I'll update in the title). the python code will check to make sure that each of these sections is up to 3 digits. so for example 123.131.10.01 it will see that this is a valid  IP address that will be flagged. but if the IP reads similar to 1214.1R3.@4#.190 it will not see this a valid IP because it notices 1. a section that has 4 symbols and 2. some sections contain none numerical symbols. I'll update the original Issue to reflect this better.
