### ISSUE TITLE
Home address detection

### ISSUE THREAD

**Issue by hsalaam** [NCATComp410/comp410_summer_2023#8]
It is important to identify and manage personal identifiable information (PII) . In this issue, I will  concentrate on identifying and safeguarding the Home address as the PII. A person's home address is  information that can be used for identity theft and other fraudulent acts.  Everyone should include safeguards out applications to recognize and protect this kind of PII.

For example:
xxxx Cooper lane, city name, state, zip code.

Detection Steps:
Python code will be developed which will compare two strings for an exact match. This code will check to if the address in string1 matches the address of string2. If the results matches the program will output true; If the the results do not match then the output will be false.

**Comment by claesmk** [comment]
Will all parts of an address need to be present or will you attempt to detect xxx Cooper Lane, zip code?

**Comment by hsalaam** [comment]
All parts of the email will be present including the city, state and zip
code

**Comment by claesmk** [comment]
Well, I don't agree.  Since the Zip code tells you the city and state just having the street address and zip could would be PII

**Comment by lb-ali** [comment]
Maybe you could include a hierarchy of the parts based on how much information it gives? First check for ZIP code, since this is easily identifiable as it is a 5 digit code, and it gives a lot of location information.
